# Introduction to Pytorch

**To install Pytorch and torchvision libray** <br>
conda install pytorch torchvision -c pytorch

In [1]:
import torch

In [3]:
print(torch.cuda.is_available())
print(torch.rand(2,2))

False
tensor([[0.2052, 0.3915],
        [0.8477, 0.7672]])


CUDA-(Compute Unifed Device  Architecture)

In [4]:
x=torch.tensor([[0,0,1],[1,1,1],[0,0,0]])

In [5]:
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [7]:
x[0][0]=5

In [8]:
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [9]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [12]:
torch.ones(1,2)+torch.ones(1,2)

tensor([[2., 2.]])

In [14]:
torch.rand(1).item()

0.7197677493095398

In [17]:
torch.rand(2,2).max().item()

0.8655259609222412

In [18]:
long_tesnor=torch.tensor([[0,0,1],[1,1,1],[0,0,0]])
long_tesnor.type()

'torch.LongTensor'

In [19]:
float_tensor=torch.tensor([[0,0,1],[1,1,1],[0,0,0]]).to(dtype=torch.float32)
float_tensor.type()

'torch.FloatTensor'

In [20]:
random_tensor=torch.rand(2,2)
random_tensor.log2()

tensor([[-0.2935, -0.5816],
        [-0.4901, -2.2993]])

In [21]:
random_tensor.log2_()  # Inplace =True Operation

tensor([[-0.2935, -0.5816],
        [-0.4901, -2.2993]])

In [22]:
random_tensor

tensor([[-0.2935, -0.5816],
        [-0.4901, -2.2993]])

Tensor Reshaping

In [24]:
flat_tensor=torch.rand(784)

In [25]:
viewed_tensor=flat_tensor.view(1,28,28)

In [28]:
viewed_tensor.shape

torch.Size([1, 28, 28])

In [29]:
reshaped_tensor=flat_tensor.reshape(1,28,28)

In [31]:
reshaped_tensor.shape

torch.Size([1, 28, 28])

In [32]:
hwc_tensor=torch.rand(640,480,3)
chw_tensor=hwc_tensor.permute(2,0,1)
chw_tensor.shape

torch.Size([3, 640, 480])

# Pytorch stores images as [channel, height, width]
# permute() can be used to deal with these

In [35]:
hwc_tensor=torch.rand(640,480,3)
chw_tensor=hwc_tensor.permute(2,0,1)
chw_tensor.shape

torch.Size([3, 640, 480])